apiVersion: v1
data:
  java_opts.conf: ""
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration monitorInterval="60">
        <Properties>
            <Property name="log-path">../logs</Property>
            <Property name="archive">${log-path}/archive</Property>
        </Properties>

        <Appenders>
            <Console name="Console-Appender" target="SYSTEM_OUT">
                <PatternLayout>
                    <pattern>
                        [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c - %msg%n
                    </pattern>>
                </PatternLayout>
            </Console>
            <RollingFile name="File-Appender"
                         fileName="${log-path}/rosapi.log"
                         filePattern="${archive}/rosapi.log.%d{yyyy-MM-dd-hh-mm}.gz">
                <PatternLayout pattern="[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c - %msg%n"/>
                <Policies>
                    <SizeBasedTriggeringPolicy size="30 MB"/>
                </Policies>
                <DefaultRolloverStrategy max="30"/>
            </RollingFile>
    <!--
            <RollingFile name="Request-Appender"
                         fileName="${log-path}/request-tracker.log"
                         filePattern="${archive}/request-tracker.log.%d{yyyy-MM-dd-hh-mm}.gz">
                <PatternLayout pattern="[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c - %msg%n"/>
                <Policies>
                    <SizeBasedTriggeringPolicy size="30 MB"/>
                </Policies>
                <DefaultRolloverStrategy max="30"/>
            </RollingFile>
    -->
            <RollingFile name="500-Exception-Appender"
                         fileName="${log-path}/500-exception.log"
                         filePattern="${archive}/500-exception.log.%d{yyyy-MM-dd-hh-mm}.gz">
                <PatternLayout pattern="[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c - %msg%n"/>
                <RegexFilter regex=".*Exception processing ticket.*" onMatch="ACCEPT" onMismatch="DENY"/>
                <Policies>
                    <SizeBasedTriggeringPolicy size="30 MB"/>
                </Policies>
                <DefaultRolloverStrategy max="30"/>
            </RollingFile>
        </Appenders>
        <Loggers>
            <Root level="warn">
                <AppenderRef ref="File-Appender" level="warn"/>
                <AppenderRef ref="Console-Appender" level="warn"/>
            </Root>
            <Logger name="org.apache.aries" level="error"/>
    <!--
            <Logger name="com.basistech.ws.logrequesttracker" level="info" additivity="false">
                <AppenderRef ref="Request-Appender"/>
            </Logger>
    -->
            <Logger name="com.basistech.ws" level="info">
                <AppenderRef ref="500-Exception-Appender" level="info"/>
            </Logger>
        </Loggers>
    </Configuration>
  logging.properties: |
    org.apache.aries.spifly = ERROR
    org.apache.cxf.bus.blueprint = ERROR
  wrapper-license.conf: |
    #encoding=UTF-8
    wrapper.license.type=DEV
    wrapper.license.id=202209270000004
    wrapper.license.licensee=Basis Technology Corp.
    wrapper.license.group=Rosette API
    wrapper.license.dev_application=Rosette Server Edition
    wrapper.license.features=pro, 64bit
    wrapper.license.upgrade_term.begin_date=2010-11-09
    wrapper.license.upgrade_term.end_date=2023-11-09
    wrapper.license.key.1=da09-c1de-5d5c-0448
    wrapper.license.key.2=57ba-c809-8b10-6f07
    wrapper.license.key.3=9ecc-8fa9-b682-bd5c
    wrapper.license.key.4=c294-c6c4-50f6-af0f
  wrapper.conf: |
    #encoding=UTF-8
    # Configuration files must begin with a line specifying the encoding
    #  of the the file.

    #********************************************************************
    # Wrapper License Properties (Ignored by Community Edition)
    #********************************************************************
    # Professional and Standard Editions of the Wrapper require a valid
    #  License Key to start.  Licenses can be purchased or a trial license
    #  requested on the following pages:
    # http://wrapper.tanukisoftware.com/purchase
    # http://wrapper.tanukisoftware.com/trial

    # Include file problems can be debugged by leaving only one '#'
    #  at the beginning of the following line:
    ##include.debug

    # The Wrapper will look for either of the following optional files for a
    #  valid License Key.  License Key properties can optionally be included
    #  directly in this configuration file.
    #include ../conf/wrapper-license.conf
    #include ../conf/wrapper-license-%WRAPPER_HOST_NAME%.conf

    # The following property will output information about which License Key(s)
    #  are being found, and can aid in resolving any licensing problems.
    #wrapper.license.debug=TRUE

    #********************************************************************
    # Wrapper Localization
    #********************************************************************
    # Specify the language and locale which the Wrapper should use.
    wrapper.lang=en_US # en_US or ja_JP

    # Specify the location of the language resource files (*.mo).
    wrapper.lang.folder=../lang

    #********************************************************************
    # Wrapper Java Properties
    #********************************************************************
    # Java Application
    #  Locate the java binary on the system PATH:
    wrapper.java.command=%JAVA_HOME%/bin/java
    #  Specify a specific java binary:
    #set.JAVA_HOME=/java/path
    #wrapper.java.command=%JAVA_HOME%/bin/java

    # Tell the Wrapper to log the full generated Java command line.
    wrapper.java.command.loglevel=INFO

    #********************************************************************
    # Basis Technology Customizations
    #********************************************************************
    wrapper.event.wrapper_start.command.argv.1=%JAVA_HOME%/bin/java
    wrapper.event.wrapper_start.command.argv.2=-jar
    wrapper.event.wrapper_start.command.argv.3=../bin/rosapi-config-preflight.jar
    wrapper.event.wrapper_start.command.argv.4=../launcher/config
    wrapper.event.wrapper_start.command.on_exit.default=SHUTDOWN
    wrapper.event.wrapper_start.command.on_exit.0=CONTINUE
    wrapper.event.wrapper_start.command.on_exit.1=SHUTDOWN
    wrapper.event.wrapper_start.command.block=TRUE
    wrapper.event.wrapper_start.command.block.action=KILL_RESTART
    wrapper.event.wrapper_start.command.block.timeout=60


    # Java Main class.  This class must implement the WrapperListener interface
    #  or guarantee that the WrapperManager class is initialized.  Helper
    #  classes are provided to do this for you.
    #  See the following page for details:
    #  http://wrapper.tanukisoftware.com/doc/english/integrate.html
    wrapper.java.mainclass=com.basistech.ws.launcher.tanuki.RosapiTanukiLauncher

    # Log level for notices about missing Java Classpath entries.
    wrapper.java.classpath.missing.loglevel=WARN

    # Java Classpath (include wrapper.jar)  Add class path elements as
    #  needed starting from 1
    wrapper.java.classpath.1=../framework/*.jar
    wrapper.java.classpath.2=../lib/wrapper.jar

    # Java Library Path (location of Wrapper.DLL or libwrapper.so)
    wrapper.java.library.path.1=../lib

    # Java Bits.  On applicable platforms, tells the JVM to run in 32 or 64-bit mode.
    #wrapper.java.additional.auto_bits=TRUE

    #********************************************************************
    # Basis Technology Customizations
    #********************************************************************
    # Rosette Enterprise will ignore 'rosapi roots' by spotting the existence of the 'roots' directory.
    # Java Additional Parameters
    wrapper.java.additional.101=-Drosapi.roots=%ROSAPI_ROOTS%
    wrapper.java.additional.102=-Dcom.sun.management.jmxremote
    #wrapper.java.additional.103=-Drosapi.cache.dir=../tmp/rosapi.cache

    # To change the default port (8181) change the port
    # below and uncomment the line.
    # NOTE:  If you used install_rosette.sh to override the port,
    #        check the bottom of this file for an existing entry.
    #wrapper.java.additional.301=-Drosapi.port=8181

    # Cloud-specific (2xx) customizations are added to the bottom this file.

    # WS-2248
    wrapper.java.additional.302=-Dorg.bytedeco.javacpp.maxPhysicalBytes=0

    # WS-2622: disable crypto-policies alignment
    # https://access.redhat.com/documentation/en-us/openjdk/17/html/configuring_openjdk_17_on_rhel_with_fips/config-fips-in-openjdk
    wrapper.java.additional.331=-Djava.security.disableSystemPropertiesFile=true

    # Logging (6xx)
    wrapper.java.additional.600=-Drosapi.framework.logger=OFF
    wrapper.java.additional.601=-Djava.util.logging.config.file=../conf/logging.properties
    wrapper.java.additional.602=-Djorg.eclipse.jetty.LEVEL=OFF
    wrapper.java.additional.603=-Dlog4j.configurationFile=../conf/log4j2.xml

    # Suppress warnings in Java 11 runtime.  Only activate with Java 9 or higher.  Remove after WS-2440
    wrapper.java.additional.711.java_version.min=9
    wrapper.java.additional.711=--add-opens=java.base/java.lang=ALL-UNNAMED
    wrapper.java.additional.712.java_version.min=9
    wrapper.java.additional.712=--add-opens=java.base/java.net=ALL-UNNAMED

    #********************************************************************
    # Basis Technology Debugging
    #********************************************************************
    # Uncomment to enable remote debugging
    #wrapper.java.additional.701=-Xdebug -Xnoagent -Djava.compiler=NONE
    #wrapper.java.additional.702=-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005

    # Consult with http://docs.oracle.com/javase/8/docs/technotes/guides/management/agent.html
    # and configure remote monitoring and management accordingly.
    #wrapper.java.additional.801=-Dcom.sun.management.jmxremote.port=1099
    # ...

    # if the below isn't set to true, the wrapper will assume process is hung while debugging
    #wrapper.java.detect_debug_jvm=true

    #********************************************************************
    # End
    #********************************************************************

    # Initial Java Heap Size (in MB)
    #wrapper.java.initmemory=3
    wrapper.java.initmemory=8192

    # Maximum Java Heap Size (in MB)
    #wrapper.java.maxmemory=64
    wrapper.java.maxmemory=16384

    # Number of seconds to allow between the time that the Wrapper launches the JVM process
    # The default value is "30 seconds".
    wrapper.startup.timeout=300

    #include ../conf/wrapper-override.conf

    #********************************************************************
    # Wrapper Logging Properties
    #********************************************************************
    # Enables Debug output from the Wrapper.
    # wrapper.debug=TRUE

    # Format of output for the console.  (See docs for formats)
    wrapper.console.format=PM

    # Log Level for console output.  (See docs for log levels)
    wrapper.console.loglevel=INFO

    # Log file to use for wrapper output logging.
    wrapper.logfile=

    # Format of output for the log file.  (See docs for formats)
    wrapper.logfile.format=LPTM

    # Log Level for log file output.  (See docs for log levels)
    wrapper.logfile.loglevel=INFO

    # Maximum size that the log file will be allowed to grow to before
    #  the log is rolled. Size is specified in bytes.  The default value
    #  of 0, disables log rolling.  May abbreviate with the 'k' (kb) or
    #  'm' (mb) suffix.  For example: 10m = 10 megabytes.
    wrapper.logfile.maxsize=10m

    # Maximum number of rolled log files which will be allowed before old
    #  files are deleted.  The default value of 0 implies no limit.
    wrapper.logfile.maxfiles=5

    # Log Level for sys/event log output.  (See docs for log levels)
    wrapper.syslog.loglevel=NONE

    #********************************************************************
    # Wrapper General Properties
    #********************************************************************
    # Allow for the use of non-contiguous numbered properties
    wrapper.ignore_sequence_gaps=TRUE

    # Do not start if the pid file already exists.
    #wrapper.pidfile.strict=TRUE

    # Title to use when running as a console
    wrapper.console.title=Rosette Server Edition

    #********************************************************************
    # Wrapper JVM Checks
    #********************************************************************
    # Detect DeadLocked Threads in the JVM. (Requires Standard Edition)
    wrapper.check.deadlock=TRUE
    wrapper.check.deadlock.interval=60
    wrapper.check.deadlock.action=RESTART
    wrapper.check.deadlock.output=FULL

    # Out Of Memory detection.
    #  Ignore -verbose:class output to avoid false positives.
    #wrapper.filter.trigger.1000=[Loaded java.lang.OutOfMemoryError
    #wrapper.filter.action.1000=NONE
    # (Simple match)
    #wrapper.filter.trigger.1001=java.lang.OutOfMemoryError
    # (Only match text in stack traces if -XX:+PrintClassHistogram is being used.)
    #wrapper.filter.trigger.1001=Exception in thread "*" java.lang.OutOfMemoryError
    #wrapper.filter.allow_wildcards.1001=TRUE
    #wrapper.filter.action.1001=RESTART
    #wrapper.filter.message.1001=The JVM has run out of memory.

    #********************************************************************
    # Basis Technology Customizations
    #********************************************************************

    # interferes with license check at top, not really wanted. Karaf should not exit.
    #wrapper.on_exit.default=RESTART
    wrapper.on_exit.3=SHUTDOWN

    # Ping timeout / interval for detecting frozen JVM
    wrapper.ping.timeout=310
    wrapper.ping.interval=10
    wrapper.ping.timeout.action=DEBUG

    #********************************************************************
    # Wrapper Email Notifications. (Requires Professional Edition)
    #********************************************************************
    # Common Event Email settings.
    #wrapper.event.default.email.debug=TRUE
    #wrapper.event.default.email.smtp.host=<SMTP_Host>
    #wrapper.event.default.email.smtp.port=25
    #wrapper.event.default.email.subject=[%WRAPPER_HOSTNAME%:%WRAPPER_NAME%:%WRAPPER_EVENT_NAME%] Event Notification
    #wrapper.event.default.email.sender=<Sender email>
    #wrapper.event.default.email.recipient=<Recipient email>

    # Configure the log attached to event emails.
    #wrapper.event.default.email.maillog=ATTACHMENT
    #wrapper.event.default.email.maillog.lines=50
    #wrapper.event.default.email.maillog.format=LPTM
    #wrapper.event.default.email.maillog.loglevel=INFO

    # Enable specific event emails.
    #wrapper.event.wrapper_start.email=TRUE
    #wrapper.event.jvm_prelaunch.email=TRUE
    #wrapper.event.jvm_start.email=TRUE
    #wrapper.event.jvm_started.email=TRUE
    #wrapper.event.jvm_deadlock.email=TRUE
    #wrapper.event.jvm_stop.email=TRUE
    #wrapper.event.jvm_stopped.email=TRUE
    #wrapper.event.jvm_restart.email=TRUE
    #wrapper.event.jvm_failed_invocation.email=TRUE
    #wrapper.event.jvm_max_failed_invocations.email=TRUE
    #wrapper.event.jvm_kill.email=TRUE
    #wrapper.event.jvm_killed.email=TRUE
    #wrapper.event.jvm_unexpected_exit.email=TRUE
    #wrapper.event.wrapper_stop.email=TRUE

    # Specify custom mail content
    #wrapper.event.jvm_restart.email.body=The JVM was restarted.\n\nPlease check on its status.\n

    #********************************************************************
    # Wrapper Windows Service Properties
    #********************************************************************
    # WARNING - Do not modify any of these properties when an application
    #  using this configuration file has been installed as a service.
    #  Please uninstall the service before modifying this section.  The
    #  service can then be reinstalled.

    # TODO: These won't be right for worker versus front-end, but Windows is not a short-term concern.

    # Name of the service
    wrapper.name=rosapi-launcher

    # Display name of the service
    wrapper.displayname=Rosette Server Edition

    # Description of the service
    wrapper.description=Rosette Server Edition

    # Service dependencies.  Add dependencies as needed starting from 1
    wrapper.ntservice.dependency.1=

    # Mode in which the service is installed.  AUTO_START, DELAY_START or DEMAND_START
    wrapper.ntservice.starttype=AUTO_START

    # Allow the service to interact with the desktop (Windows NT/2000/XP only).
    wrapper.ntservice.interactive=FALSE

    # Allow the current user to perform certain actions without being prompted for
    #  administrator credentials. (Requires Professional Edition)
    #wrapper.ntservice.permissions.1.account=CURRENT_USER
    #wrapper.ntservice.permissions.1.allow=START, STOP, PAUSE_RESUME
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: rosette-pv-conf-configmap
