apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rosette-pv-roots-claim
  labels:
    app: rosette-pv
    env: test
spec:
  selector:
    matchLabels:
      app: rosette-pv
      env: test
  storageClassName: default
  volumeName: rosette-pv-roots-volume
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 150G