{{- if (eq .Values.apikeys.enabled true) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "rosette-server.fullname" . }}-apikeys-db-scaling-role
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    resourceNames: [ {{ print (include "rosette-server.fullname" .) "-apikeys-db-server" | quote }}]
    verbs: ["get", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    resourceNames: [ {{ print (include "rosette-server.fullname" .) "-apikeys-db-server-0" | quote }}]
    verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rosette-server.fullname" . }}-apikeys-db-scaling-sa
  labels:
    {{- include "rosette-server.labels" . | nindent 4 }}
  {{- with .Values.apikeys.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "rosette-server.fullname" . }}-apikeys-db-scaling-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "rosette-server.fullname" . }}-apikeys-db-scaling-role
subjects:
  - kind: ServiceAccount
    name: {{ include "rosette-server.fullname" . }}-apikeys-db-scaling-sa
{{- end }}