{{- if (eq .Values.apikeys.enabled true) }}
{{- if .Values.apikeys.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rosette-server-apikeys.serviceAccountName" . }}
  labels:
    {{- include "rosette-server.labels" . | nindent 4 }}
  {{- with .Values.apikeys.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
