apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "rosette-server.fullname" . }}
  labels:
    {{- include "rosette-server.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "rosette-server.fullname" . }}-deployment
  minReplicas: {{ .Values.horizontalLoadBalancer.targetMinReplicas }}
  maxReplicas: {{ .Values.horizontalLoadBalancer.targetMaxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.horizontalLoadBalancer.targetCPUUtilizationPercent }}