apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "rosette-server.fullname" . }}-roots-volume
  labels:
    {{- include "rosette-server.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 150G
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.nfsServer.rootsMountPoint }}
    server: {{ .Values.nfsServer.address }}
